# Generated by Django 3.1 on 2020-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leneva_backend', '0004_auto_20200809_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Vegtables'), ('F', 'Fruit'), ('O', 'Others')], max_length=2),
        ),
    ]
