# Generated by Django 3.1 on 2020-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leneva_backend', '0012_auto_20200809_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inside_cart',
            field=models.BooleanField(default=False),
        ),
    ]
